### ISSUE TITLE
Question about generate_data.py

### ISSUE THREAD

**Issue by hyunseoki** [walsvid/CoordConv#6]
Although it does not affect the final results, 
please consider this minor change in your code to reflect the original paper contents

It will be helpful for debugging

paper :
```
## bias is basically neglected in tensorflow
onehots = np.pad(np.eye(3136).reshape((3136, 56, 56, 1)), ((0,0), (4,4), (4,4), (0,0)), "constant");  
images = tf.nn.conv2d(onehots, np.ones((9, 9, 1, 1)), [1]*4, "SAME")
```

code as is :
https://github.com/walsvid/CoordConv/blob/647bcfeace2a5755f0f121eb9931c4098575fc88/experiments/generate_data.py#L25

code to be:

```
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(9, 9), padding=4, stride=1, bias=False)
```

**Comment by walsvid** [comment]
Thanks for your reminder, I will try to update the relevant code.
